"""empty message

Revision ID: b8a7c0d32f35
Revises: 
Create Date: 2023-02-20 14:38:17.184866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8a7c0d32f35'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitar_coleta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('quantidade', sa.String(length=2), nullable=False),
    sa.Column('situacao', sa.String(length=50), nullable=True),
    sa.Column('descricao', sa.String(length=100), nullable=True),
    sa.Column('criado', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solicitar_coleta')
    # ### end Alembic commands ###
